apiVersion: v1
kind: Namespace
metadata:
  name: bgomes-namespace
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-deployment
  namespace: bgomes-namespace
  labels:
    app: flask
spec:
  replicas: 2
  selector:
    matchLabels:
      app: flask
  template:
    metadata:
      labels:
        app: flask
    spec:
      
      containers:
      - name: flask
        image: bjgomes/flaskapp
        ports:
        - containerPort: 5000
        imagePullPolicy: Always
        

---
